Repository codestates-seb/seb42_main_016, pull requests merged in 2023-03, with the labels that each got.

#17 [추가] Review 패키지 1차 구현 완료 (2023.03.10 김창하)
  udog_server/.gitignore
  udog_server/src/main/java/com/mainproject/udog_server/review/controller/ReviewController.java
  udog_server/src/main/java/com/mainproject/udog_server/review/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/review/entity/Review.java
  udog_server/src/main/java/com/mainproject/udog_server/review/mapper/ReviewMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/review/repository/ReviewRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/review/service/ReviewService.java
  udog_server/src/main/java/com/mainproject/udog_server/reviewLike/controller/ReviewLikeController.java
  udog_server/src/main/java/com/mainproject/udog_server/reviewLike/dto/ReviewLikeDto.java
  udog_server/src/main/java/com/mainproject/udog_server/reviewLike/entity/ReviewLike.java
  udog_server/src/main/java/com/mainproject/udog_server/reviewLike/mapper/ReviewLikeMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/reviewLike/repository/ReviewLikeRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/reviewLike/service/ReviewLikeService.java
Labels: 개발

#19 [추가] dog 기본 CRUD 기능 추가(2023.03.10 엄영준)
  udog_server/.gitignore
  udog_server/src/main/java/com/mainproject/udog_server/dog/controller/DogController.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/dto/DogDto.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/entity/Dog.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/mapper/DogMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/repository/DogRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/service/DogService.java
  udog_server/src/main/java/com/mainproject/udog_server/utils/UriCreator.java
Labels: 개발

#20 [병합] Login, Security, Member API (2023.03.10 이상윤)
  udog_server/.gitignore
  udog_server/build.gradle
  udog_server/src/main/generated/com/mainproject/udog_server/api/member/MemberMapperImpl.java
  udog_server/src/main/java/com/mainproject/udog_server/UdogServerApplication.java
  udog_server/src/main/java/com/mainproject/udog_server/api/member/Member.java
  udog_server/src/main/java/com/mainproject/udog_server/api/member/MemberController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/member/MemberDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/member/MemberMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/api/member/MemberRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/api/member/MemberService.java
  udog_server/src/main/java/com/mainproject/udog_server/audit/Auditable.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/LoginDto.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/MemberDetailsService.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/SecurityConfiguration.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/filter/JwtAuthenticationFilter.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/handler/MemberAuthenticationFailureHandler.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/handler/MemberAuthenticationSuccessHandler.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/utils/CustomAuthorityUtils.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/utils/JwtTokenizer.java
  udog_server/src/main/java/com/mainproject/udog_server/response/ErrorResponse.java
  udog_server/src/main/java/com/mainproject/udog_server/response/ExceptionCode.java
  udog_server/src/main/resources/application.properties
  udog_server/src/main/resources/application.yml
Labels: 개발

#23 [수정] Review 변수명 리팩토링 (2023.03.11 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/review/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/review/entity/Review.java
  udog_server/src/main/java/com/mainproject/udog_server/api/review/service/ReviewService.java
Labels: 리팩토링

#25 [병합] 로그인, 회원가입, 헤어샵, 강아지정보, 모달 추가 (2023.03.13 신수현)
  client/.gitignore
  client/data.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/AddCard.js
  client/src/components/DogCard.js
  client/src/components/DogForm.js
  client/src/components/DogList.js
  client/src/components/Empty.js
  client/src/components/HairshopList.js
  client/src/components/Location.js
  client/src/components/LoginForm.js
  client/src/components/SignupForm.js
  client/src/components/modal/DogConfirmModal.js
  client/src/components/modal/TypeModal.js
  client/src/components/modal/WeightModal.js
  client/src/components/style/CardStyle.js
  client/src/components/style/DogStyle.js
  client/src/components/style/EmptyStyle.js
  client/src/components/style/FormStyle.js
  client/src/components/style/GlobalStyle.js
  client/src/components/style/ListStyle.js
  client/src/components/style/ModalStyle.js
  client/src/hooks/useAxios.js
  client/src/hooks/useConfirmPassword.js
  client/src/hooks/useDelete.js
  client/src/hooks/useDogAge.js
  client/src/hooks/useEmail.js
  client/src/hooks/useFetch.js
  client/src/hooks/useGeolocation.js
  client/src/hooks/useNickname.js
  client/src/hooks/usePassword.js
  client/src/hooks/useScroll.js
  client/src/index.js
  client/src/modules/API.js
  client/src/modules/ModalContainer.js
  client/src/modules/redux/deleteSlice.js
  client/src/modules/redux/dogSlice.js
  client/src/modules/redux/editSlice.js
  client/src/modules/redux/emptySlice.js
  client/src/modules/redux/modalSlice.js
  client/src/modules/redux/store.js
  client/src/modules/redux/userSlice.js
  client/src/pages/DeleteHome.js
  client/src/pages/Hairshop.js
  client/src/pages/Login.js
  client/src/pages/Mydog.js
  client/src/pages/MydogEditor.js
  client/src/pages/Signup.js
  client/src/utils/AddButton.js
  client/src/utils/CloseIcon.js
  client/src/utils/ModalOption.js
  client/src/utils/img.jpeg
Labels: 개발

#26 [수정] 모달 삭제버튼 이벤트 핸들러 수정 (2023.03.13 신수현)
  client/src/components/modal/DogConfirmModal.js
Labels: 개발

#31 [수정] 강아지 생년월일 유효성 수정 (2023.03.13 신수현)
  client/src/hooks/useDogAge.js
Labels: 개발

#41 [병합] 사이드바, 탑버튼 연결 및 파일구조 변경
  client/src/components/hairshop/HairshopList.js
  client/src/components/hairshop/Location.js
  client/src/components/mydog/AddCard.js
  client/src/components/mydog/DogCard.js
  client/src/components/mydog/DogForm.js
  client/src/components/mydog/DogList.js
  client/src/components/mypage/MypageSidebar.js
  client/src/components/style/DogStyle.js
  client/src/pages/Hairshop.js
  client/src/pages/Mydog.js
  client/src/pages/MydogEditor.js
Labels: 개발

#46 [추가] 무한 스크롤 추가 (2023.03.13 신수현)
  client/data.json
  client/src/App.js
  client/src/components/hairshop/HairshopList.js
  client/src/components/hairshop/Location.js
  client/src/components/style/ListStyle.js
  client/src/hooks/useAxios.js
  client/src/hooks/useDelete.js
  client/src/hooks/useFetch.js
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useScroll.js
  client/src/pages/Hairshop.js
  client/src/pages/HairshopDetail.js
Labels: 개발

#50 [추가] 미용실 상세페이지 홈 탭 추가 (2023.03.14 신수현)
  client/src/App.js
  client/src/components/Loading.js
  client/src/components/hairshop/HairshopList.js
  client/src/components/mydog/AddCard.js
  client/src/components/mydog/DogCard.js
  client/src/components/style/DogStyle.js
  client/src/components/style/FormStyle.js
  client/src/components/style/HomeStyle.js
  client/src/components/style/ListStyle.js
  client/src/components/style/TabBarStyle.js
  client/src/components/tab/BookTab.js
  client/src/components/tab/HomeTab.js
  client/src/components/tab/ReviewTab.js
  client/src/hooks/useFetch.js
  client/src/hooks/useInfiniteScroll.js
  client/src/modules/redux/loadingSlice.js
  client/src/modules/redux/store.js
  client/src/modules/redux/tabSlice.js
  client/src/pages/Hairshop.js
  client/src/pages/HairshopDetail.js
  client/src/pages/Mydog.js
  client/src/pages/MydogEditor.js
  client/src/utils/AddButton.js
  client/src/utils/ClockIcon.js
  client/src/utils/CloseIcon.js
  client/src/utils/PhoneIcon.js
  client/src/utils/ReviewIcon.js
Labels: 개발

#51 [추가] 로그인 하러가기 모달 추가 (2023.03.15 신수현)
  client/public/index.html
  client/src/App.js
  client/src/components/modal/IsLoginModal.js
  client/src/components/mydog/DogForm.js
  client/src/components/style/ModalStyle.js
  client/src/components/tab/HomeTab.js
  client/src/index.js
  client/src/modules/ModalContainer.js
  client/src/modules/redux/userSlice.js
Labels: 개발

#57 [수정] api 명세서에 맞게 강아지 정보, 미용실페이지 변수명 수정 (2023.03.15 신수현)
  client/data.json
  client/src/App.js
  client/src/components/hairshop/HairshopList.js
  client/src/components/modal/TypeModal.js
  client/src/components/modal/WeightModal.js
  client/src/components/mydog/AddCard.js
  client/src/components/mydog/DogCard.js
  client/src/components/mydog/DogForm.js
  client/src/components/mydog/DogList.js
  client/src/components/style/HomeStyle.js
  client/src/components/tab/HomeTab.js
  client/src/hooks/useInfiniteScroll.js
  client/src/modules/redux/dogSlice.js
  client/src/modules/redux/likeSlice.js
  client/src/modules/redux/modalSlice.js
  client/src/modules/redux/store.js
  client/src/pages/Hairshop.js
  client/src/pages/HairshopDetail.js
Labels: 개발

#60 [추가] 마이페이지 GET 요청 커스텀 훅 추가 (2023.03.15 신수현)
  client/src/App.js
  client/src/hooks/useAuth.js
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useLike.js
Labels: 개발

#61 [추가] 미용실 좋아요 추가 (2023.03.15 신수현)
  client/data.json
  client/src/components/hairshop/HairshopList.js
  client/src/components/modal/DogConfirmModal.js
  client/src/components/mydog/DogCard.js
  client/src/components/tab/HomeTab.js
  client/src/hooks/useComment.js
  client/src/hooks/useLike.js
  client/src/hooks/useShopLike.js
  client/src/modules/redux/deleteSlice.js
  client/src/modules/redux/likeSlice.js
  client/src/modules/redux/setSlice.js
  client/src/modules/redux/shopSlice.js
  client/src/modules/redux/store.js
  client/src/pages/HairshopDetail.js
Labels: 개발

#66 [추가] 내 정보관리 추가 (2023.03.16 신수현)
  client/src/App.js
  client/src/components/mydog/DogCard.js
  client/src/components/myinfo/MyContent.js
  client/src/components/myinfo/MyUser.js
  client/src/components/style/DogStyle.js
  client/src/components/style/MyInfoStyle.js
  client/src/components/tab/HomeTab.js
  client/src/pages/MyInfo.js
  client/src/pages/MypageMyInfo.js
Labels: 개발

#68 [추가] 마이페이지 추가 (2023.03.16 신수현)
  client/src/components/myinfo/MyContent.js
  client/src/components/myinfo/MyDogContent.js
  client/src/components/myinfo/MyReserveContent.js
  client/src/components/myinfo/MyReviewContent.js
  client/src/components/myinfo/Withdraw.js
  client/src/components/style/CardStyle.js
  client/src/components/style/MyInfoStyle.js
  client/src/pages/MyInfo.js
Labels: 개발

#72 [수정] 미용실 좋아요 api 수정, 강아지 카드 라우팅 경로 수정 (2023.03.16 신수현)
  client/src/components/mydog/DogCard.js
  client/src/hooks/useShopLike.js
  client/src/pages/MyInfo.js
  client/src/pages/Mydog.js
  client/src/pages/MydogEditor.js
Labels: 개발

#71 [리팩토링] DogCompositeService 적용 (2023.03.16 엄영준)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/DogCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/DogController.java
Labels: 리팩토링

#69 [리팩토링] ReviewCompositeService 적용 (2023.03.16 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReviewController.java
Labels: 리팩토링

#67 [리팩토링] member & hairshop composite service 적용 완료(2023.03.16 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/MemberCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/HairShopController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/MemberController.java
  udog_server/src/main/java/com/mainproject/udog_server/member/MemberService.java
Labels: 리팩토링

#74 [리팩토링] 상수 관리, 옵셔널 체이닝 적용 (2023.03.16 신수현)
  client/src/App.js
  client/src/components/LoginForm.js
  client/src/components/SignupForm.js
  client/src/components/hairshop/HairshopList.js
  client/src/components/modal/LoginModal.js
  client/src/components/mydog/AddCard.js
  client/src/components/mydog/DogCard.js
  client/src/components/mydog/DogForm.js
  client/src/components/mydog/DogList.js
  client/src/components/myinfo/MyDogContent.js
  client/src/components/myinfo/MyReserveContent.js
  client/src/components/myinfo/MyReviewContent.js
  client/src/components/tab/HomeTab.js
  client/src/hooks/useComment.js
  client/src/hooks/useScrollTop.js
  client/src/hooks/useShopLike.js
  client/src/modules/ModalContainer.js
  client/src/modules/endpoints.js
  client/src/modules/routes.js
  client/src/pages/Hairshop.js
  client/src/pages/HairshopDetail.js
  client/src/pages/MyInfo.js
  client/src/pages/Mydog.js
  client/src/pages/MydogEditor.js
Labels: 개발

#75 [리팩토링] ReviewLikeDto 병합: static class로 관리 (2023.03.16 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReviewLikeController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReviewLikeResponseDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReviewLikeMapper.java
Labels: 리팩토링

#81 [리팩토링] Dog BirthDate Dto->DB 수정(2023.03.16 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/DogController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/DogDto.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/Dog.java
Labels: 리팩토링

#92 [추가] 회원탈퇴, 스타일북 무한스크롤 & 좋아요 추가 (2023.03.17 신수현)
  client/data.json
  client/src/components/modal/HomeModal.js
  client/src/components/modal/WithdrawConfirmModal.js
  client/src/components/mydog/DogForm.js
  client/src/components/myinfo/Withdraw.js
  client/src/components/style/HomeStyle.js
  client/src/components/style/MyInfoStyle.js
  client/src/components/style/SBStyle.js
  client/src/components/stylebook/StylebookItem.js
  client/src/components/stylebook/StylebookList.js
  client/src/components/tab/HomeTab.js
  client/src/hooks/useAxios.js
  client/src/hooks/useReviewLike.js
  client/src/hooks/useShopLike.js
  client/src/modules/ModalContainer.js
  client/src/modules/redux/dogSlice.js
  client/src/modules/redux/emptySlice.js
  client/src/modules/redux/reviewsSlice.js
  client/src/modules/redux/shopSlice.js
  client/src/modules/redux/store.js
  client/src/pages/Stylebook.js
Labels: 개발

#95 [추가&리팩토링] StyleLike API 추가, Review API에서 ReviewLike 제거 완료(2023.03.17 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewLikeCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/StyleBookCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/StyleLikeCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReviewController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReviewLikeController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/StyleBookController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/StyleLikeController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/StyleLikeDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/StyleResponseDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReviewLikeMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/StyleLikeMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/review/Review.java
  udog_server/src/main/java/com/mainproject/udog_server/reviewLike/ReviewLikeRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/reviewLike/ReviewLikeService.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLike.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLikeRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLikeService.java
Labels: 개발, 리팩토링

#98 [추가&리팩토링] ReviewController CrossOrigin 어노테이션 추가, Review 관련 import 와일드카드 및 주석 제거 (2023.03.17 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReviewController.java
  udog_server/src/main/java/com/mainproject/udog_server/review/Review.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewService.java
Labels: 개발, 리팩토링

#100 [추가][리팩토링][에러] 스타일북 기능 추가 및 연관관계 수정 및 에러 수정(2023.03.17 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/StyleBookCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/StyleBookController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/StyleBookResponseDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/StyleResponseDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReviewMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/StyleBookMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/StyleLikeMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShop.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshopLike/HairShopLikeRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/review/Review.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewService.java
  udog_server/src/main/java/com/mainproject/udog_server/styleBook/StyleBookRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/styleBook/StyleBookService.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLikeRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLikeService.java
Labels: 버그, 개발, 리팩토링

#99 [추가&리팩토링] Review 디렉토리 구조 변경에 따른 Test 코드 수정, API 명세서 작성(v1.0.0) (2023.03.17 김창하)
  udog_server/src/docs/asciidoc/index.adoc
  udog_server/src/main/resources/static/docs/index.html
  udog_server/src/test/java/com/mainproject/udog_server/restdocs/review/ReviewControllerRestDocsTest.java
  udog_server/src/test/java/com/mainproject/udog_server/restdocs/reviewLike/ReviewLikeControllerRestDocsTest.java
Labels: 개발, 리팩토링

#102 [추가] 헤더, 메인페이지 (2023.03.17)
  client/package-lock.json
  client/src/.eslintrc.json
  client/src/.prettier.json
  client/src/.prettierrc.json
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/LoginHeader.js
  client/src/components/MPstylebook/StylebookItem.js
  client/src/components/MPstylebook/StylebookList.js
  client/src/components/MPstylebook/TopButton.js
  client/src/components/modal/NickChangeModal.js
  client/src/components/modal/TypeModal.js
  client/src/components/modal/WeightModal.js
  client/src/components/mydog/DogForm.js
  client/src/components/myinfo/MyUser.js
  client/src/components/style/FooterStyle.js
  client/src/components/style/HeaderStyle.js
  client/src/components/style/SBStyle.js
  client/src/pages/MainPage.js
  client/src/pages/Myreview.js
  client/src/pages/Stylebook.js
Labels: 개발

#105 [병합] 모든 컴포넌트 연결, CSS 통일화 (2023.03.17 신수현)
  client/src/.eslintrc.json
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/myinfo/MyDogContent.js
  client/src/components/myinfo/MyReserveContent.js
  client/src/components/myinfo/MyReviewContent.js
  client/src/components/myinfo/Withdraw.js
  client/src/components/mypage/MypageSidebar.js
  client/src/components/style/DogStyle.js
  client/src/components/style/FooterStyle.js
  client/src/components/style/HeaderStyle.js
  client/src/components/style/MyInfoStyle.js
  client/src/components/style/MyPageStyle.js
  client/src/components/style/SBStyle.js
  client/src/components/stylebook/TopButton.js
  client/src/modules/routes.js
  client/src/pages/DeleteHome.js
  client/src/pages/Hairshop.js
  client/src/pages/HairshopDetail.js
  client/src/pages/MainPage.js
  client/src/pages/MyInfo.js
  client/src/pages/Mypage.js
  client/src/pages/Stylebook.js
Labels: 리팩토링

#106 [추가] 로그아웃 기능 추가 (2023.03.17 신수현)
  client/src/App.js
  client/src/components/Header.js
  client/src/components/MPstylebook/StylebookItem.js
  client/src/components/MPstylebook/StylebookList.js
  client/src/components/MPstylebook/TopButton.js
  client/src/components/hairshop/HairshopList.js
  client/src/components/mainpage/BestShopList.js
  client/src/components/mainpage/BestStyleList.js
  client/src/components/modal/LogoutConfirmModal.js
  client/src/components/style/ListStyle.js
  client/src/components/style/MainStyle.js
  client/src/components/style/SBStyle.js
  client/src/modules/ModalContainer.js
  client/src/pages/Hairshop.js
  client/src/pages/MainPage.js
Labels: 개발

#109 [추가]리뷰전체조회 -> 특정미용실리뷰전체조회로 변경(2023.03.17)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReviewController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewService.java
Labels: 개발

#111 [수정] Review hairShop 추가에 의한 테스트 코드 변경 (2023.03.17 김창하)
  udog_server/src/main/resources/static/docs/index.html
  udog_server/src/test/java/com/mainproject/udog_server/restdocs/review/ReviewControllerRestDocsTest.java
Labels: 개발

#115 [수정] 전체적인 eslint, 라우팅 에러 수정 (2023.03.17 신수현)
  client/.eslintrc.json
  client/.prettierrc.json
  client/data.json
  client/src/.eslintrc.json
  client/src/.prettier.json
  client/src/.prettierrc.json
  client/src/App.js
  client/src/components/Header.js
  client/src/components/LoginForm.js
  client/src/components/hairshop/HairshopList.js
  client/src/components/hairshop/Location.js
  client/src/components/hairshopreview/HairshopReview.js
  client/src/components/hairshopreview/Pagenation.js
  client/src/components/mainpage/BestShopList.js
  client/src/components/mainpage/BestStyleList.js
  client/src/components/modal/HomeModal.js
  client/src/components/modal/LoginModal.js
  client/src/components/modal/LogoutConfirmModal.js
  client/src/components/modal/TypeModal.js
  client/src/components/modal/WeightModal.js
  client/src/components/modal/WithdrawConfirmModal.js
  client/src/components/mydog/DogCard.js
  client/src/components/mydog/DogForm.js
  client/src/components/myinfo/MyReserveContent.js
  client/src/components/myinfo/MyReviewContent.js
  client/src/components/myinfo/Withdraw.js
  client/src/components/mypage/MypageSidebar.js
  client/src/components/mypageReview/ReserveItem.js
  client/src/components/style/HomeStyle.js
  client/src/components/style/ListStyle.js
  client/src/components/style/MyPageStyle.js
  client/src/components/style/ShopRevewStyle.js
  client/src/components/tab/BookTab.js
  client/src/components/tab/ReviewTab.js
  client/src/hooks/useAxios.js
  client/src/hooks/useReviewLike.js
  client/src/index.js
  client/src/modules/API.js
  client/src/modules/endpoints.js
  client/src/modules/redux/dogSlice.js
  client/src/modules/redux/shopSlice.js
  client/src/modules/routes.js
  client/src/pages/Hairshop.js
  client/src/pages/HairshopDetail.js
  client/src/pages/MyInfo.js
  client/src/pages/Myreserve.js
  client/src/pages/Myreview.js
  client/src/pages/Stylebook.js
Labels: 리팩토링

#116 [수정] 스타일북 라우팅추가, 관련 훅 수정 (2023.03.18 신수현)
  client/data.json
  client/src/components/LoginHeader.js
  client/src/components/mainpage/BestStyleList.js
  client/src/components/style/HeaderStyle.js
  client/src/components/stylebook/StylebookItem.js
  client/src/components/stylebook/StylebookList.js
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useReviewLike.js
  client/src/modules/redux/dogSlice.js
  client/src/pages/Stylebook.js
Labels: 개발

#119 [추가] Reservation 기본 구조 생성 (2023.03.18 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReservationCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReservationController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReservationDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReservationMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/Reservation.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationService.java
Labels: 개발

#130 [추가] RDS 설정 완료(2023.03.18 이상윤)
  udog_server/build.gradle
  udog_server/src/main/resources/application-deploy.properties
  udog_server/src/main/resources/application-deploy.yml
  udog_server/src/main/resources/application-local.yml
  udog_server/src/main/resources/application.yml
Labels: 개발

#133 [추가] RDS 설정 완료(2023.03.18 이상윤)
  udog_server/build.gradle
  udog_server/src/main/resources/application-deploy.properties
  udog_server/src/main/resources/application-deploy.yml
  udog_server/src/main/resources/application.yml
  udog_server/src/main/resources/static/docs/index.html
Labels: 개발

#136 [추가] 상세페이지 리뷰 탭 추가 (2023.03.18 신수현)
  client/data.json
  client/package-lock.json
  client/package.json
  client/src/components/hairshopreview/HairshopReview.js
  client/src/components/hairshopreview/Pagenation.js
  client/src/components/hairshopreview/ShopReview.js
  client/src/components/style/HomeStyle.js
  client/src/components/style/ShopRevewStyle.js
  client/src/components/style/TabBarStyle.js
  client/src/components/tab/HomeTab.js
  client/src/components/tab/ReviewTab.js
  client/src/modules/redux/editSlice.js
  client/src/modules/redux/modalSlice.js
  client/src/modules/redux/reserveSlice.js
  client/src/modules/redux/setSlice.js
  client/src/modules/redux/tabSlice.js
  client/src/modules/redux/userSlice.js
  client/src/pages/HairshopDetail.js
  client/src/pages/MyInfo.js
  client/src/utils/sample.jpeg
Labels: 개발

#141 [에러] 비밀번호 변경 에러 해결(2023.03.19 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/MemberCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/MemberController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/MemberDto.java
  udog_server/src/main/resources/static/docs/index.html
Labels: 버그

#143 [추가] styleBook response에 내가 좋아요 누른 게시물의 styleLikeId 담기(2023.03.19 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/StyleBookCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/StyleBookController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/StyleBookResponseDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/StyleBookMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/review/Review.java
Labels: 개발

#148 [추가] 상세페이지 예약탭 추가 (2023.03.20 신수현)
  client/package-lock.json
  client/package.json
  client/src/components/hairshopreserve/Calender.js
  client/src/components/hairshopreserve/DesignOption.js
  client/src/components/hairshopreserve/MyDogList.js
  client/src/components/mydog/DogCard.js
  client/src/components/style/CalenderStyle.js
  client/src/components/style/HomeStyle.js
  client/src/components/style/ReserveStyle.js
  client/src/components/tab/BookTab.js
  client/src/modules/redux/bookSlice.js
  client/src/modules/redux/store.js
  client/src/utils/StyleOption.js
  client/src/utils/getDogAge.js
Labels: 개발

#149 [추가] 미용실 Top10 response에 hairShopLikeId 추가(2023.03.20 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/HairShopDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/HairShopMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShop.java
Labels: 개발

#154 [추가]로그인상태 미용실 상세 get 시 set 유저의 likeId(2023.03.20 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/HairShopController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/DogDto.java
Labels: 버그

#153 [추가] 로딩 컴포넌트 추가 (2023.03.20 신수현)
  client/package-lock.json
  client/package.json
  client/src/components/Loading.js
  client/src/components/hairshopreserve/Calender.js
  client/src/components/hairshopreserve/DesignOption.js
  client/src/components/hairshopreserve/MyDogList.js
  client/src/components/mainpage/BestShopList.js
  client/src/components/mainpage/BestStyleList.js
  client/src/components/modal/LogoutConfirmModal.js
  client/src/components/mydog/DogCard.js
  client/src/components/mydog/DogForm.js
  client/src/components/mydog/DogList.js
  client/src/components/stylebook/StylebookItem.js
  client/src/components/tab/HomeTab.js
  client/src/hooks/useAxios.js
  client/src/hooks/useFetch.js
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useNickname.js
  client/src/hooks/useReviewLike.js
  client/src/hooks/useShopLike.js
  client/src/modules/redux/dogSlice.js
  client/src/modules/redux/likeSlice.js
  client/src/modules/redux/shopSlice.js
  client/src/modules/redux/userSlice.js
  client/src/pages/Hairshop.js
  client/src/pages/HairshopDetail.js
  client/src/pages/MainPage.js
  client/src/pages/Mypage.js
  client/src/pages/Stylebook.js
  client/src/utils/BookOption.js
Labels: 개발

#161 [리팩토링] 네이밍, date 객체, 로딩 컴포넌트 리팩토링 (2023.03.21 신수현)
  client/src/App.js
  client/src/components/hairshopreserve/Calender.js
  client/src/components/hairshopreserve/DesignOption.js
  client/src/components/hairshopreserve/MyDogList.js
  client/src/components/hairshopreview/ShopReview.js
  client/src/components/stylebook/StylebookItem.js
  client/src/components/tab/ReviewTab.js
  client/src/hooks/useDogAge.js
  client/src/hooks/useInfiniteScroll.js
  client/src/modules/redux/bookSlice.js
  client/src/pages/Hairshop.js
  client/src/pages/HairshopDetail.js
  client/src/pages/MainPage.js
  client/src/pages/Mypage.js
  client/src/pages/Stylebook.js
Labels: 리팩토링

#163 [수정] shop 리듀서 수정, 리뷰 없음 적용 (2023.03.21 신수현)
  client/src/components/tab/HomeTab.js
  client/src/components/tab/ReviewTab.js
  client/src/modules/redux/shopSlice.js
Labels: 개발

#167 [추가] 푸터, 토스트 알럿 추가 (2023.03.22 신수현)
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/LoginForm.js
  client/src/components/SignupForm.js
  client/src/components/hairshopreserve/Calender.js
  client/src/components/modal/BookConfirmModal.js
  client/src/components/myinfo/MyDogContent.js
  client/src/components/style/CalenderStyle.js
  client/src/components/style/FooterStyle.js
  client/src/components/style/ListStyle.js
  client/src/components/style/MyInfoStyle.js
  client/src/components/tab/BookTab.js
  client/src/hooks/useAxios.js
  client/src/modules/ModalContainer.js
  client/src/modules/redux/errorSlice.js
  client/src/modules/redux/store.js
  client/src/modules/routes.js
  client/src/pages/HairshopDetail.js
  client/src/pages/Mypage.js
Labels: 개발

#165 [수정,추가] 예약의 필드 중 수정해야 될 타입들 수정, dog와의 연관관계 수정, 등록-조회-삭제 포스트맨으로 요청 및 응답 확인 완료 (2023.03.22 엄영준)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/DogCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReservationCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/DogController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/HairShopController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReservationController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/DogDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/HairShopDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReservationDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/DogMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReservationMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/Dog.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/DogService.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShop.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/Reservation.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationService.java
  udog_server/src/main/java/com/mainproject/udog_server/review/Review.java
  udog_server/src/test/java/com/mainproject/udog_server/restdocs/dog/DogControllerRestDocsTest.java
Labels: 개발, 리팩토링

#160 [추가] reviewImage Multipart 적용 (2023.03.22 김창하)
  udog_server/.gitignore
  udog_server/build.gradle
  udog_server/src/main/generated/com/mainproject/udog_server/api/mapper/ReviewMapperImpl.java
  udog_server/src/main/java/com/mainproject/udog_server/UdogServerApplication.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReviewController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReviewMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewService.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/component/S3Component.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/config/S3Config.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/service/AWSS3UploadService.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/service/FileUploadService.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/service/UploadService.java
  udog_server/src/main/resources/application-aws.yml
  udog_server/src/main/resources/application-credentials.yml
  udog_server/src/main/resources/application.yml
Labels: 개발

#168 [추가] 로고, 위치 기본값 추가 (2023.03.23 신수현)
  client/.eslintrc.json
  client/public/assets/Logo.png
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/LoginForm.js
  client/src/components/SignupForm.js
  client/src/components/hairshop/Location.js
  client/src/components/hairshopreserve/Calender.js
  client/src/components/style/FooterStyle.js
  client/src/components/style/FormStyle.js
  client/src/components/style/HeaderStyle.js
  client/src/modules/redux/dogSlice.js
  client/src/modules/routes.js
  client/src/pages/Mypage.js
Labels: 개발

#169 [수정] 로고, 탑버튼 css 수정 (2023.03.23 신수현)
  client/src/components/style/HeaderStyle.js
  client/src/components/style/SBStyle.js
Labels: 개발

#171 [추가] 서비스 소개 추가 (2023.03.24 신수현)
  client/public/assets/Book.png
  client/public/assets/Shop.png
  client/public/assets/Style.png
  client/public/assets/Top.png
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/style/AboutStyle.js
  client/src/components/style/ListStyle.js
  client/src/components/tab/HomeTab.js
  client/src/modules/routes.js
  client/src/pages/About.js
Labels: 개발

#173 [추가] 예약된 시간 응답으로 보내기 기능 및 리뷰가 없는 예약 내역 보내는 기능 추가(2023.03.24 엄영준)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/DogCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReservationCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/DogController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReservationController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReservationDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReservationMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/DogRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/DogService.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/Reservation.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationService.java
  udog_server/src/main/java/com/mainproject/udog_server/review/Review.java
Labels: 개발

#178 [추가] 미용실 거리순 나열 고정값으로 구현(2023.03.24 이상윤)
  udog_server/build.gradle
  udog_server/libs/javaproj-1.0.6.jar
  udog_server/src/main/generated/com/mainproject/udog_server/api/mapper/ReservationMapperImpl.java
  udog_server/src/main/generated/com/mainproject/udog_server/api/mapper/StyleBookMapperImpl.java
  udog_server/src/main/generated/com/mainproject/udog_server/api/mapper/StyleLikeMapperImpl.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/HairShopController.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetController.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetService.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/ExcelList.java
  udog_server/src/main/java/com/mainproject/udog_server/districtOffice/DistrictOffice.java
  udog_server/src/main/java/com/mainproject/udog_server/districtOffice/DistrictOfficeController.java
  udog_server/src/main/java/com/mainproject/udog_server/districtOffice/DistrictOfficeRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/districtOffice/DistrictOfficeService.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShop.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopService.java
  udog_server/src/main/java/com/mainproject/udog_server/util/DistanceCalculator.java
  udog_server/src/main/resources/h2/schema.sql
  udog_server/src/main/resources/static/docs/index.html
Labels: 개발

#182 [수정] 스타일 top3 (2023.03.24 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/StyleBookCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/styleBook/StyleBookRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/styleBook/StyleBookService.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLike.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLikeRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLikeService.java
Labels: 개발

#192 [추가] 예약 api 추가 (2023.03.24 신수현)
  client/src/components/hairshopreserve/Calender.js
  client/src/components/hairshopreserve/MyDogList.js
  client/src/components/modal/BookConfirmModal.js
  client/src/components/modal/HomeModal.js
  client/src/components/modal/LoginModal.js
  client/src/components/modal/ReviewEditModal.js
  client/src/components/modal/ReviewModal.js
  client/src/components/modal/TypeModal.js
  client/src/components/modal/WeightModal.js
  client/src/components/style/CalenderStyle.js
  client/src/components/tab/BookTab.js
  client/src/hooks/useFetch.js
  client/src/modules/endpoints.js
Labels: 개발

#193 [수정] 예약 disabled 수정 (2023.03.25 신수현)
  client/src/components/hairshopreserve/Calender.js
Labels: 버그

#195 [추가] 닉네임 변경 모달 추가 (2023.03.24 신수현)
  client/src/components/modal/NickChangeModal.js
  client/src/components/modal/NickModal.js
  client/src/components/myinfo/MyUser.js
  client/src/components/style/ModalStyle.js
  client/src/modules/ModalContainer.js
  client/src/modules/redux/userSlice.js
Labels: 개발

#188 [추가] GET memberReviews, GET hairShopReviews 추가 (2023.03.24 김창하)
  udog_server/src/main/generated/com/mainproject/udog_server/api/mapper/ReviewMapperImpl.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReviewController.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReviewMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewService.java
Labels: 개발

#197 [수정] Reservation Resonse Dto에 HairShopId 추가(2023.03.25 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReservationDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReservationMapper.java
  udog_server/src/main/resources/h2/schema.sql
Labels: 리팩토링

#200 [수정]강아지 견종 수정 추가, 위생미용 띄어쓰기 제거, hairOption 필드에 nullable = false 추가 (2…
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReservationCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/DogDto.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/Reservation.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationService.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewService.java
  udog_server/src/test/java/com/mainproject/udog_server/restdocs/dog/DogControllerRestDocsTest.java
  udog_server/src/test/java/com/mainproject/udog_server/restdocs/dog/MemberControllerRestDocsTest.java
  udog_server/src/test/java/com/mainproject/udog_server/restdocs/review/ReviewControllerRestDocsTest.java
  udog_server/src/test/java/com/mainproject/udog_server/util/ApiDocumentUtils.java
Labels: 개발

#199 [수정] GET memberReview의 hairShopId, GET hairShopReview의 memberId 나오게 하기 (2023.03.25 김창하)
  udog_server/src/main/generated/com/mainproject/udog_server/api/mapper/ReviewLikeMapperImpl.java
  udog_server/src/main/generated/com/mainproject/udog_server/api/mapper/ReviewMapperImpl.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReviewMapper.java
Labels: 개발

#205 [버그, 수정] review 삭제 안되는 부분, reservation 삭제 시 hairShop도 같이 삭제되는 부분 수정 (2023.03.25 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/reservation/Reservation.java
  udog_server/src/main/java/com/mainproject/udog_server/review/Review.java
Labels: 버그, 개발

#208 [추가] memberReviews 조회 시 response에 hairShopName 추가 (2023.03.25 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReviewMapper.java
Labels: 개발

#209 [추가] 비밀번호 변경 추가 (2023.03.25 신수현)
  client/src/components/modal/NickModal.js
  client/src/components/modal/PasswordModal.js
  client/src/components/myinfo/MyUser.js
  client/src/components/style/AboutStyle.js
  client/src/components/style/ListStyle.js
  client/src/components/style/ModalStyle.js
  client/src/hooks/useReviewLike.js
  client/src/modules/ModalContainer.js
  client/src/pages/About.js
Labels: 개발

#210 [버그] reservation의 hairShopId와 review의 hairShopId가 같을 때만 review POST되게 수정 (2023.03.25 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
Labels: 버그, 개발

#212 [버그] reservation의 memberId와 review의 memberId가 같을 때만 review POST되게 수정 (2023.03.25 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
Labels: 버그, 개발

#215 [수정] 이미지 url, css 수정 (2023.03.25 신수현)
  client/src/components/hairshop/HairshopList.js
  client/src/components/mypage/MypageSidebar.js
  client/src/components/mypageReview/ReviewItem.js
  client/src/components/mypageReview/ReviewTab.js
  client/src/components/style/ModalStyle.js
  client/src/components/style/MyPageStyle.js
  client/src/components/style/ReviewStyle.js
  client/src/components/tab/HomeTab.js
  client/src/pages/Prepare.js
Labels: 개발

#213 [버그] reservation에 대한 review가 없을 때만 review POST 가능하도록 수정 (2023.03.25 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
Labels: 버그, 개발

#216 [수정] 현재시간 지난 버튼 disabled, get 두번 요청 수정 (2023.03.25 신수현)
  client/data.json
  client/src/components/Footer.js
  client/src/components/hairshopreserve/Calender.js
  client/src/components/mypage/MypageSidebar.js
  client/src/components/mypageReview/ReviewTab.js
  client/src/components/style/ShopRevewStyle.js
  client/src/components/tab/HomeTab.js
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useShopLike.js
  client/src/hooks/useShopScroll.js
  client/src/modules/API.js
  client/src/modules/redux/likeSlice.js
  client/src/modules/redux/shopSlice.js
  client/src/pages/About.js
  client/src/pages/Hairshop.js
  client/src/pages/Stylebook.js
  client/src/utils/img.jpeg
  client/src/utils/sample.jpeg
Labels: 개발

#218 [수정] 내 주변 미용실 에러 수정 (2023.03.26 신수현)
  client/src/components/hairshop/Location.js
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useShopScroll.js
  client/src/modules/redux/locationSlice.js
  client/src/pages/Hairshop.js
  client/src/pages/Stylebook.js
Labels: 버그

#219 [추가] empty 컴포넌트 연결 (2023.03.26 신수현)
  client/src/components/mypage/ReserveList.js
  client/src/components/mypageReview/MyReviewList.js
  client/src/components/mypageReview/WriteReview.js
Labels: 개발

#220 [추가] 나의 정보 예약, 리뷰 요약정보 연결 (2023.03.26 신수현)
  client/src/components/myinfo/MyReserveContent.js
  client/src/components/myinfo/MyReviewContent.js
Labels: 개발

#221 [수정] 중복된 데이터, 서비스 소개 사진 수정 (2023.03.26 신수현)
  client/public/assets/Best.png
  client/public/assets/Shop.png
  client/public/assets/Style.png
  client/src/pages/About.js
  client/src/pages/Hairshop.js
Labels: 개발

#217 [추가] selenium으로 imgurl 크롤링 구현(2023.03.26 이상윤)
  udog_server/build.gradle
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopService.java
  udog_server/src/main/resources/application.yml
Labels: 개발

#222 [수정] 구청 로직 빼고 내주변미용실 구현 완료(2023.03.26 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopService.java
Labels: 개발

#224 [수정] 회원 탈퇴 로직, 닉네임 변경 유효성 수정 (2023.03.26 신수현)
  client/src/components/modal/NickModal.js
  client/src/components/modal/WithdrawConfirmModal.js
  client/src/hooks/useAxios.js
Labels: 개발

#225 [수정] 미용실 모든 get api count 일괄 적용(2023.03.26 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopService.java
Labels: 개발, 리팩토링

#226 [수정] member status 탈퇴 조회 로직 (2023.03.26 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/member/MemberService.java
Labels: 리팩토링

#228 [추가][수정] 탈퇴회원 관리(2023.03.26 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/MemberCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/MemberController.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/MemberDetailsService.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/filter/JwtAuthenticationFilter.java
  udog_server/src/main/java/com/mainproject/udog_server/member/MemberService.java
Labels: 버그, 개발, 리팩토링

#229 [수정] 미용실 무한 스크롤 수정 (2023.03.26 신수현)
  client/src/hooks/useShopScroll.js
  client/src/pages/Hairshop.js
Labels: 개발

#233 [수정] 테이블 명세서 기반 테이블 관련 수정 (2023.03.27 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/dog/Dog.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/Reservation.java
  udog_server/src/main/java/com/mainproject/udog_server/review/Review.java
  udog_server/src/main/java/com/mainproject/udog_server/styleLike/StyleLike.java
Labels: 개발

#236 [추가, 수정] 이미지 준비중 추가, css 수정 (2023.03.27 신수현)
  client/public/assets/Img.png
  client/src/components/hairshop/HairshopList.js
  client/src/components/mypage/PagenationR.js
  client/src/components/mypage/ReserveList.js
  client/src/components/mypageReview/MyReviewList.js
  client/src/components/mypageReview/ReviewItem.js
  client/src/components/style/MyPageStyle.js
  client/src/components/style/ReviewStyle.js
  client/src/components/tab/HomeTab.js
  client/src/modules/redux/reserveSlice.js
  client/src/modules/redux/reviewsSlice.js
Labels: 개발

#237 [추가] 리뷰 없는 예약 내역들 페이지네이션 기능 추가(2023.03.27 엄영준)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReservationCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/controller/ReservationController.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationService.java
Labels: 개발

#239 [수정] districtOffice 컬럼들 nullable = false로 수정 (2023.03.27 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/districtOffice/DistrictOffice.java
Labels: 개발

#240 [수정] css 수정 (2023.03.27 신수현)
  client/.eslintrc.json
  client/.gitignore
  client/src/components/LoginForm.js
  client/src/components/SignupForm.js
  client/src/components/hairshopreview/Pagenation.js
  client/src/components/modal/NickModal.js
  client/src/components/modal/PasswordModal.js
  client/src/components/style/HomeStyle.js
  client/src/components/style/ListStyle.js
  client/src/components/style/MyPageStyle.js
  client/src/components/style/ReviewStyle.js
  client/src/components/style/SBStyle.js
  client/src/components/tab/BookTab.js
  client/src/components/tab/HomeTab.js
  client/src/components/tab/ReviewTab.js
  client/src/hooks/useAuth.js
  client/src/hooks/useAxios.js
  client/src/hooks/useDelete.js
  client/src/hooks/useFetch.js
  client/src/hooks/useReviewLike.js
  client/src/hooks/useShopLike.js
  client/src/modules/redux/errorSlice.js
  client/src/modules/redux/messageSlice.js
  client/src/modules/redux/store.js
Labels: 리팩토링

#243 [수정] 스크롤 범위 수정 (2023.03.28 신수현)
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useShopScroll.js
Labels: 개발

#244 [수정] S3 재설정 및 db 초기화(2023.03.28 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/s3/service/AWSS3UploadService.java
  udog_server/src/main/resources/application-aws.yml
  udog_server/src/main/resources/application.yml
  udog_server/src/main/resources/h2/schema.sql
Labels: 개발, 리팩토링

#246 [추가] hairShopReviewsResponse에 nickname, hairOption 추가 (2023.03.28 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/ReviewDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/ReviewMapper.java
Labels: 개발, 리팩토링

#250 [수정] 설정 수정 (2023.03.29 신수현)
  client/package.json
Labels: 개발

#251 [수정] data 수정 (2023.03.29 신수현)
  client/src/components/hairshopreview/ShopReview.js
Labels: 개발

#252 [리팩토링] 주석제거, 스타일 분리 (2023.03.29 신수현)
  client/src/components/style/AboutStyle.js
  client/src/pages/Myreview.js
  client/src/pages/Prepare.js
Labels: 리팩토링

#253 [리팩토링] 리덕스 적용 (2023.03.29 신수현)
  client/src/hooks/useGeolocation.js
  client/src/modules/redux/messageSlice.js
Labels: 리팩토링

#254 [수정] css 수정 (2023.03.29 신수현)
  client/src/components/style/ReviewStyle.js
Labels: 개발

#255 [수정] css 수정 (2023.03.29 신수현)
  client/src/components/mainpage/BestStyleList.js
Labels: 개발

#263 [수정] 이미지, 유효성 변경 (2023.03.29 신수현)
  client/public/assets/Img.png
  client/public/assets/ShopImg.png
  client/src/components/hairshop/HairshopList.js
  client/src/components/hairshopreserve/Calender.js
  client/src/components/mydog/DogForm.js
  client/src/components/style/HomeStyle.js
  client/src/components/style/MainStyle.js
  client/src/components/tab/BookTab.js
  client/src/components/tab/HomeTab.js
  client/src/hooks/useDogAge.js
Labels: 개발

#264 [수정] 의존성 배열 추가 (2023.03.29 신수현)
  client/README.md
  client/src/components/myinfo/MyReviewContent.js
Labels: 개발

#266 [수정] MemberDto & ProjectTimeZone(2023.03.29 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/UdogServerApplication.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/MemberDto.java
Labels: 개발, 리팩토링

#268 [수정] 변수 수정, 주석 삭제 (2023.03.30 신수현)
  client/src/components/modal/ReviewEditModal.js
  client/src/components/myinfo/MyReserveContent.js
Labels: 개발

#269 [병합] 클라이언트 2차 병합
  client/src/components/modal/ReviewEditModal.js
  client/src/components/myinfo/MyReserveContent.js
Labels: 개발

#270 [추가, 리팩토링] review 삭제 시 S3 bucket에 있는 이미지 파일도 삭제 (2023.03.30 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/service/AWSS3UploadService.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/service/UploadService.java
Labels: 개발, 리팩토링

#272 [추가] 좋아요 개수 추가 (2023.03.30 신수현)
  client/src/components/style/SBStyle.js
  client/src/components/stylebook/StylebookItem.js
  client/src/hooks/useReviewLike.js
Labels: 개발

#273 [수정] 리뷰 수정 리듀서 추가 (2023.03.30 신수현)
  client/src/components/modal/ReviewEditModal.js
  client/src/components/modal/ReviewModal.js
  client/src/components/myinfo/MyReviewContent.js
  client/src/components/mypageReview/MyReviewList.js
  client/src/modules/redux/reviewsSlice.js
Labels: 개발

#276 [추가] 미용실 link 데이터 추가(2023.03.30 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/HairShopDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/HairShopMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetNaverCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShop.java
Labels: 개발, 리팩토링

#278 [병합] 클라이언트 4차 병합
  client/src/components/style/HomeStyle.js
  client/src/components/tab/HomeTab.js
Labels: 개발

#281 [수정] 위치 에러 수정 (2023.03.31 신수현)
  client/src/hooks/useGeolocation.js
  client/src/hooks/useShopScroll.js
  client/src/modules/redux/locationSlice.js
  client/src/modules/redux/messageSlice.js
  client/src/pages/Hairshop.js
Labels: 개발

#283 [수정] css 수정 (2023.03.31 신수현)
  client/src/components/style/HomeStyle.js
  client/src/components/style/ListStyle.js
Labels: 개발

#287 [추가] 유효시간 만료 알림 추가 (2023.03.31 신수현)
  client/src/components/TokenChecker.js
  client/src/modules/redux/messageSlice.js
Labels: 개발

#288 [추가] ReadMe 완료(2023.03.31 이상윤)
  README.md
  images/project_background.png
  images/project_intro.png
  images/project_tech_tree.png
  images/udog_image.png
Labels: 문서

#289 [수정] 무한스크롤 옵저버 API로 변경, 이동 버튼, 기준 설명 추가 (2023.03.31 신수현)
  client/src/components/style/AboutStyle.js
  client/src/components/style/MainStyle.js
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useShopScroll.js
  client/src/modules/redux/scrollSlice.js
  client/src/modules/redux/store.js
  client/src/pages/About.js
  client/src/pages/Hairshop.js
  client/src/pages/MainPage.js
  client/src/pages/Stylebook.js
Labels: 개발

#291 [추가] 리뷰 작성 안내문구 추가 (2023.03.31 신수현)
  client/public/assets/Best.png
  client/public/assets/BestTop.png
  client/public/assets/HairShop.png
  client/public/assets/Shop.png
  client/src/components/Header.js
  client/src/components/mypageReview/WriteReview.js
  client/src/components/style/HeaderStyle.js
  client/src/components/style/MyPageStyle.js
  client/src/pages/MainPage.js
Labels: 개발

#292 [병합] 클라이언트 5차 병합
  client/public/assets/Best.png
  client/public/assets/BestTop.png
  client/public/assets/HairShop.png
  client/public/assets/Shop.png
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/LoginForm.js
  client/src/components/TokenChecker.js
  client/src/components/mypage/ReserveItem.js
  client/src/components/mypageReview/WriteReview.js
  client/src/components/style/AboutStyle.js
  client/src/components/style/HeaderStyle.js
  client/src/components/style/HomeStyle.js
  client/src/components/style/ListStyle.js
  client/src/components/style/MainStyle.js
  client/src/components/style/MyPageStyle.js
  client/src/hooks/useGeolocation.js
  client/src/hooks/useInfiniteScroll.js
  client/src/hooks/useShopScroll.js
  client/src/modules/redux/locationSlice.js
  client/src/modules/redux/messageSlice.js
  client/src/modules/routes.js
  client/src/pages/About.js
  client/src/pages/BestPage.js
  client/src/pages/Hairshop.js
  client/src/pages/MainPage.js
  client/src/pages/Stylebook.js
Labels: 개발
