Repository codestates-seb/seb42_main_016, pull requests merged in 2023-04, with the labels that each got.

#286 [추가] accessToken 만료시 refreshToken을 통한 AccessToken 재발급 로직 (2023.03.31 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/auth/filter/JwtVerificationFilter.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/utils/CustomAuthorityUtils.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/utils/JwtTokenizer.java
  udog_server/src/main/java/com/mainproject/udog_server/exception/ExceptionCode.java
Labels: 개발

#293 [리팩토링] REVIEW 예외코드 적용 (2023.04.02 김창하)
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/exception/ExceptionCode.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewService.java
Labels: 리팩토링

#295 [추가] 스타일, 미용실 top 스케줄러 구현(2023.04.03 이상윤)
  udog_server/src/main/java/com/mainproject/udog_server/UdogServerApplication.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/StyleBookCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopService.java
  udog_server/src/main/java/com/mainproject/udog_server/styleBook/StyleBookRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/styleBook/StyleBookService.java
  udog_server/src/main/java/com/mainproject/udog_server/topHairShop/TopHairShop.java
  udog_server/src/main/java/com/mainproject/udog_server/topHairShop/TopHairShopRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/topHairShop/TopHairShopService.java
  udog_server/src/main/java/com/mainproject/udog_server/topStyle/TopStyle.java
  udog_server/src/main/java/com/mainproject/udog_server/topStyle/TopStyleRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/topStyle/TopStyleService.java
  udog_server/src/main/resources/h2/data.sql
  udog_server/src/main/resources/h2/schema.sql
Labels: 개발, 리팩토링

#297 [수정] 베스트 기준 수정 (2023.04.03 신수현)
  client/src/pages/BestPage.js
Labels: 개발

#298 [배포] 배포 5차 백엔드 데모데이 버전
  udog_server/src/main/java/com/mainproject/udog_server/UdogServerApplication.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/HairShopCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReservationCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/ReviewCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/composite_service/StyleBookCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/api/dto/HairShopDto.java
  udog_server/src/main/java/com/mainproject/udog_server/api/mapper/HairShopMapper.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/filter/JwtVerificationFilter.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/utils/CustomAuthorityUtils.java
  udog_server/src/main/java/com/mainproject/udog_server/auth/utils/JwtTokenizer.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/dataSetApi/DataSetNaverCompositeService.java
  udog_server/src/main/java/com/mainproject/udog_server/dog/DogService.java
  udog_server/src/main/java/com/mainproject/udog_server/exception/ExceptionCode.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShop.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/hairshop/HairShopService.java
  udog_server/src/main/java/com/mainproject/udog_server/reservation/ReservationService.java
  udog_server/src/main/java/com/mainproject/udog_server/review/ReviewService.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/service/AWSS3UploadService.java
  udog_server/src/main/java/com/mainproject/udog_server/s3/service/UploadService.java
  udog_server/src/main/java/com/mainproject/udog_server/styleBook/StyleBookRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/styleBook/StyleBookService.java
  udog_server/src/main/java/com/mainproject/udog_server/topHairShop/TopHairShop.java
  udog_server/src/main/java/com/mainproject/udog_server/topHairShop/TopHairShopRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/topHairShop/TopHairShopService.java
  udog_server/src/main/java/com/mainproject/udog_server/topStyle/TopStyle.java
  udog_server/src/main/java/com/mainproject/udog_server/topStyle/TopStyleRepository.java
  udog_server/src/main/java/com/mainproject/udog_server/topStyle/TopStyleService.java
  udog_server/src/main/resources/h2/schema.sql
Labels: 개발, 리팩토링

#300 [추가] best 라우팅, 스타일북 안내문구 추가 (2023.04.12 신수현)
  client/src/components/Empty.js
  client/src/components/mainpage/BestShopList.js
  client/src/components/mainpage/BestStyleList.js
  client/src/components/style/EmptyStyle.js
  client/src/components/style/SBStyle.js
  client/src/pages/Stylebook.js
Labels: 리팩토링

#302 [수정] 베스트 스타일 오류 수정 (2023.04.15 신수현)
  client/src/components/mainpage/BestStyleList.js
Labels: 리팩토링

#303 [수정] 스타일북 오류 수정 (2023.04.15 신수현)
  client/src/pages/Stylebook.js
Labels: 리팩토링
